### ISSUE TITLE
Add execution as attachments in the Test Run

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#8]

**Comment by ManelMoreno** [comment]
We need to detail what is this issue referred to. If you mean that the allure report containing the execution exported to a PDF, should be attached to the JAMA Test Run, when uplading the Test Result, yes, it is a good idea.

But even better could be to insert a sentence with the path to the location of this reports and/or other evidences. We try to avoid the attachements in JAMA in order to preserve the tool performance.

**Comment by ManelMoreno** [comment]
Nowadays this request is no more needed.
